# MongoDB Configuration File - Node 3 (Secondary)
# Port: 27019

# Where and how to store data
storage:
  dbPath: /home/aakash/Desktop/DevOpsBootcamp/week2/day5/stack1_next_node_mongodb/mongodb-replicaset/data/node3

# Where to write logging data
systemLog:
  destination: file
  logAppend: true
  path: /home/aakash/Desktop/DevOpsBootcamp/week2/day5/stack1_next_node_mongodb/mongodb-replicaset/logs/mongod-node3.log

# Network interfaces
net:
  port: 27019
  bindIp: 127.0.0.1

# Process management
processManagement:
  fork: true
  pidFilePath: /home/aakash/Desktop/DevOpsBootcamp/week2/day5/stack1_next_node_mongodb/mongodb-replicaset/mongod-node3.pid

# Security
security:
  authorization: enabled
  keyFile: /home/aakash/Desktop/DevOpsBootcamp/week2/day5/stack1_next_node_mongodb/mongodb-replicaset/config/replica-keyfile

# Replication
replication:
  replSetName: rs0
