services:

  backend:
    build:
      context: ../3_tier_app/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      LOG_LEVEL: error
    restart: unless-stopped

  frontend:
    build:
      context: ../3_tier_app/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"  
    restart: unless-stopped