services:

  backend:
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ../3_tier_app/backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
    command: node --watch index.js

  frontend:
    build:
      context: ../3_tier_app/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ../3_tier_app/frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: "5173"
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:5173 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 60s