[program:fastapi-mysql-api]
; Supervisor config for FastAPI MySQL API
; Place at: /etc/supervisor/conf.d/fastapi-mysql-api.conf
; Reload: supervisorctl reread && supervisorctl update

command=/home/user/.pyenv/versions/3.11.7/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4
directory=/home/aakash/Desktop/DevOpsBootcamp/week2/day4/fastapi-mysql-api
user=aakash
autostart=true
autorestart=true
startretries=5
startsecs=10
stopwaitsecs=30
stopsignal=TERM

stderr_logfile=/home/aakash/Desktop/DevOpsBootcamp/week2/day4/fastapi-mysql-api/var/log/apps/fastapi-supervisor-error.log
stdout_logfile=/home/aakash/Desktop/DevOpsBootcamp/week2/day4/fastapi-mysql-api/var/log/apps/fastapi-supervisor-access.log

stderr_logfile_maxbytes=10MB
stdout_logfile_maxbytes=10MB
stderr_logfile_backups=5
stdout_logfile_backups=5
environment=PYTHONPATH="/home/aakash/Desktop/DevOpsBootcamp/week2/day4/fastapi-mysql-api",PYTHONUNBUFFERED="1"