[program:fastapi-mysql-api]
; Updated to your actual local path
command=/home/aakash/Desktop/DevOpsBootcamp/week2/day4/fastapi-mysql-api/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4 --log-level info

directory=/home/aakash/Desktop/DevOpsBootcamp/week2/day4/fastapi-mysql-api

; Change to your username so it has permission to read the Desktop folder
user=aakash

autostart=true
autorestart=true
startretries=5
startsecs=10

stopsignal=TERM
stopwaitsecs=30

; Absolute paths to log files 
stderr_logfile=/home/aakash/Desktop/DevOpsBootcamp/week2/day4/fastapi-mysql-api/error.log
stdout_logfile=/home/aakash/Desktop/DevOpsBootcamp/week2/day4/fastapi-mysql-api/access.log
stderr_logfile_maxbytes=10MB
stdout_logfile_maxbytes=10MB

environment=PYTHONPATH="/home/aakash/Desktop/DevOpsBootcamp/week2/day4/fastapi-mysql-api",PYTHONUNBUFFERED="1",APP_ENV="production"