const BASE  = '/home/aakash/Desktop/DevOpsBootcamp/week2/day5/stack1_next_node_mongodb';
const MONGO = 'mongodb://devops:Devops%40123@localhost:27017,localhost:27018,localhost:27019/usersdb?replicaSet=rs0&authSource=admin&readPreference=primaryPreferred&retryWrites=true&w=majority';

module.exports = {
  apps: [

    // Backend — Node.js Express API (PM2 cluster mode)
    // 3 instances on ports 3000, 3003, 3004
    {
      name: 'backend-3000',
      script: './server.js',
      cwd: `${BASE}/backend`,
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV:    'production',
        PORT:        3000,
        MONGODB_URI: MONGO,
        LOG_LEVEL:   'info',
        LOG_DIR:     './var/log/apps',
        RATE_LIMIT_MAX_REQUESTS: 100,
        CORS_ORIGIN: 'https://stack1.devops.local',
      },
      error_file:      `${BASE}/backend/var/log/apps/express-api-pm2-error-0.log`,
      out_file:        `${BASE}/backend/var/log/apps/express-api-pm2-out-0.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs:   true,
      autorestart:  true,
      max_restarts: 10,
      min_uptime:   '10s',
      watch:        false,
      kill_timeout: 5000,
    },
    {
      name: 'backend-3003',
      script: './server.js',
      cwd: `${BASE}/backend`,
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV:    'production',
        PORT:        3003,
        MONGODB_URI: MONGO,
        LOG_LEVEL:   'info',
        LOG_DIR:     './var/log/apps',
        RATE_LIMIT_MAX_REQUESTS: 100,
        CORS_ORIGIN: 'https://stack1.devops.local',
      },
      error_file:      `${BASE}/backend/var/log/apps/express-api-pm2-error-3.log`,
      out_file:        `${BASE}/backend/var/log/apps/express-api-pm2-out-3.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs:   true,
      autorestart:  true,
      max_restarts: 10,
      min_uptime:   '10s',
      watch:        false,
      kill_timeout: 5000,
    },
    {
      name: 'backend-3004',
      script: './server.js',
      cwd: `${BASE}/backend`,
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV:    'production',
        PORT:        3004,
        MONGODB_URI: MONGO,
        LOG_LEVEL:   'info',
        LOG_DIR:     './var/log/apps',
        RATE_LIMIT_MAX_REQUESTS: 100,
        CORS_ORIGIN: 'https://stack1.devops.local',
      },
      error_file:      `${BASE}/backend/var/log/apps/express-api-pm2-error-4.log`,
      out_file:        `${BASE}/backend/var/log/apps/express-api-pm2-out-4.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs:   true,
      autorestart:  true,
      max_restarts: 10,
      min_uptime:   '10s',
      watch:        false,
      kill_timeout: 5000,
    },

    // Frontend — Next.js SSR (PM2 fork mode)
    // 2 instances on ports 3001, 3002
    {
      name: 'frontend-3001',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3001',
      cwd: `${BASE}/frontend`,
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV:            'production',
        PORT:                3001,
        NEXT_PUBLIC_API_URL: 'https://stack1.devops.local',
      },
      error_file:      `${BASE}/frontend/var/log/nextjs-pm2-error-1.log`,
      out_file:        `${BASE}/frontend/var/log/nextjs-pm2-out-1.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs:   true,
      autorestart:  true,
      max_restarts: 10,
      min_uptime:   '10s',
      watch:        false,
      kill_timeout: 5000,
    },
    {
      name: 'frontend-3002',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3002',
      cwd: `${BASE}/frontend`,
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV:            'production',
        PORT:                3002,
        NEXT_PUBLIC_API_URL: 'https://stack1.devops.local',
      },
      error_file:      `${BASE}/frontend/var/log/nextjs-pm2-error-2.log`,
      out_file:        `${BASE}/frontend/var/log/nextjs-pm2-out-2.log`,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs:   true,
      autorestart:  true,
      max_restarts: 10,
      min_uptime:   '10s',
      watch:        false,
      kill_timeout: 5000,
    },

  ],
};
