#!/bin/bash
set -euo pipefail

# Script: server-provision.sh
# Description: Provisions a new server end-to-end: inventory, users, DNS client,
#              firewall, security hardening, and logging infrastructure
# Author: Aakash
# Date: 2026-02-17
# Usage: sudo ./server-provision.sh [OPTIONS]

# Exit codes
readonly EXIT_SUCCESS=0
readonly EXIT_ERROR=1

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROVISION_SCRIPTS="${SCRIPT_DIR}/server-provision_scripts"

REPORT_DIR="${SCRIPT_DIR}/reports"
TIMESTAMP="$(date '+%Y-%m-%d_%H-%M-%S')"
REPORT_FILE="${REPORT_DIR}/server-provision-${TIMESTAMP}.txt"

LOG_FILE="${SCRIPT_DIR}/var/log/apps/server-provision.log"

mkdir -p "$REPORT_DIR" "$(dirname "$LOG_FILE")"

# Logging functions
log_info() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] $1" | tee -a "$LOG_FILE"
    logger -t "server-provision" -p local0.info "$1" 2>/dev/null || true
}

log_error() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [ERROR] $1" | tee -a "$LOG_FILE" >&2
    logger -t "server-provision" -p local0.err "$1" 2>/dev/null || true
}

log_warn() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] [WARN] $1" | tee -a "$LOG_FILE"
    logger -t "server-provision" -p local0.warning "$1" 2>/dev/null || true
}

log_section() {
    local msg="$1"
    echo "" | tee -a "$LOG_FILE"
    echo "==================================================" | tee -a "$LOG_FILE"
    echo "$msg" | tee -a "$LOG_FILE"
    echo "==================================================" | tee -a "$LOG_FILE"
}

# Write section header to report
write_section() {
    {
        echo ""
        echo "=================================================="
        echo "$1"
        echo "=================================================="
        echo ""
    } >> "$REPORT_FILE"
}

# Run a provisioning script
run_script() {
    local description="$1"
    local script_path="$2"
    shift 2

    log_info "Running: $description"

    if [[ ! -x "$script_path" ]]; then
        log_warn "[SKIPPED] Not executable or not found: $script_path"
        echo "[SKIPPED] $description" >> "$REPORT_FILE"
        return
    fi

    if "$script_path" "$@"; then
        log_info "✓ $description completed"
    else
        local code=$?
        log_warn "✗ $description exited with status $code"
        echo "[WARN] $description exited with non-zero status ($code)" >> "$REPORT_FILE"
    fi
}

# Help function
show_usage() {
    cat << EOF
Usage: sudo $(basename "$0") [OPTIONS]

Provisions a server end-to-end:
  1. Runs system inventory
  2. Provisions users from users.txt
  3. Configures DNS client settings (resolv.conf)
  4. Sets up UFW firewall from firewall_rules.csv
  5. Applies security hardening from config files
  6. Deploys centralized logging and log rotation

All scripts are sourced from: server-provision_scripts/

OPTIONS:
    -h, --help          Show this help message
    -n, --dry-run       Validate and report only, no changes applied
    --skip-users        Skip user provisioning
    --skip-firewall     Skip firewall setup
    --skip-hardening    Skip security hardening
    --skip-logging      Skip logging setup

Examples:
    sudo $(basename "$0")
    sudo $(basename "$0") --dry-run
    sudo $(basename "$0") --skip-users
EOF
}

# Configure DNS client resolv.conf
configure_dns_client() {
    log_info "Configuring DNS client settings"
    write_section "DNS CLIENT CONFIGURATION"

    local resolv_conf="/etc/resolv.conf"
    local dns_server="192.168.1.10"
    local domain="devops.lab"

    if [[ "$DRY_RUN" == true ]]; then
        log_info "[DRY-RUN] Would write $resolv_conf:"
        log_info "  search $domain"
        log_info "  nameserver $dns_server"
        echo "[DRY-RUN] DNS client: nameserver $dns_server, search $domain" >> "$REPORT_FILE"
        return
    fi

    # Backup existing resolv.conf
    if [[ -f "$resolv_conf" ]]; then
        cp "$resolv_conf" "${resolv_conf}.bak.$(date +%Y%m%d_%H%M%S)"
    fi

    cat > "$resolv_conf" << EOF
# Generated by server-provision.sh on $(date)
search $domain
nameserver $dns_server
nameserver 8.8.8.8
EOF

    log_info "DNS client configured: nameserver=$dns_server, search=$domain"
    echo "DNS nameserver: $dns_server" >> "$REPORT_FILE"
    echo "DNS search domain: $domain" >> "$REPORT_FILE"
}

# Main function
main() {
    if [[ "$EUID" -ne 0 ]]; then
        log_error "This script must be run as root"
        exit $EXIT_ERROR
    fi

    # Initialize report
    {
        echo "===================================================="
        echo "         SERVER PROVISIONING REPORT"
        echo "===================================================="
        echo "Generated : $(date)"
        echo "Hostname  : $(hostname)"
        echo "Report ID : server-provision-${TIMESTAMP}"
        echo "Dry Run   : ${DRY_RUN}"
        echo "===================================================="
    } > "$REPORT_FILE"

    log_section "SERVER PROVISIONING STARTED"
    log_info "Report file: $REPORT_FILE"
    log_info "Scripts directory: $PROVISION_SCRIPTS"

    # ── Step 1: System Inventory ──────────────────────────
    log_section "STEP 1: SYSTEM INVENTORY"
    write_section "STEP 1: SYSTEM INVENTORY"
    run_script "System Inventory" \
        "${PROVISION_SCRIPTS}/system_inventory.sh" \
        --report "$REPORT_FILE"

    # ── Step 2: User Provisioning ─────────────────────────
    if [[ "${SKIP_USERS:-false}" != true ]]; then
        log_section "STEP 2: USER PROVISIONING"
        write_section "STEP 2: USER PROVISIONING"
        local users_file="${PROVISION_SCRIPTS}/users.txt"
        if [[ -f "$users_file" ]]; then
            run_script "User Provisioning" \
                "${PROVISION_SCRIPTS}/user_provision.sh" \
                "$users_file"
            echo "Users file: $users_file" >> "$REPORT_FILE"
        else
            log_warn "users.txt not found at $users_file — skipping user provisioning"
            echo "[SKIPPED] users.txt not found" >> "$REPORT_FILE"
        fi
    fi

    # ── Step 3: DNS Client Configuration ─────────────────
    log_section "STEP 3: DNS CLIENT CONFIGURATION"
    configure_dns_client

    # ── Step 4: Firewall Setup ────────────────────────────
    if [[ "${SKIP_FIREWALL:-false}" != true ]]; then
        log_section "STEP 4: FIREWALL SETUP"
        write_section "STEP 4: FIREWALL SETUP"
        local ufw_args=""
        [[ "$DRY_RUN" == true ]] && ufw_args="--dry-run"
        run_script "UFW Firewall Setup" \
            "${PROVISION_SCRIPTS}/ufw_setup.sh" \
            ${ufw_args:+"$ufw_args"}
    fi

    # ── Step 5: Security Hardening ────────────────────────
    if [[ "${SKIP_HARDENING:-false}" != true ]]; then
        log_section "STEP 5: SECURITY HARDENING"
        write_section "STEP 5: SECURITY HARDENING"
        local hardening_args=""
        [[ "$DRY_RUN" == true ]] && hardening_args="--dry-run"
        run_script "Security Hardening" \
            "${PROVISION_SCRIPTS}/security_hardening.sh" \
            ${hardening_args:+"$hardening_args"}
    fi

    # ── Step 6: Logging Infrastructure ───────────────────
    if [[ "${SKIP_LOGGING:-false}" != true ]]; then
        log_section "STEP 6: LOGGING INFRASTRUCTURE"
        write_section "STEP 6: LOGGING INFRASTRUCTURE"
        local logging_args=""
        [[ "$DRY_RUN" == true ]] && logging_args="--dry-run"
        run_script "Logging Setup" \
            "${PROVISION_SCRIPTS}/setup_logging.sh" \
            ${logging_args:+"$logging_args"}
    fi

    # ── Final Summary ─────────────────────────────────────
    {
        echo ""
        echo "===================================================="
        echo "             PROVISIONING SUMMARY"
        echo "===================================================="
        echo "Completed : $(date)"
        echo "Report    : $REPORT_FILE"
        echo "Log       : $LOG_FILE"
        echo "===================================================="
    } | tee -a "$REPORT_FILE"

    log_section "SERVER PROVISIONING COMPLETED"
    log_info "Report saved to: $REPORT_FILE"
}

# Parse arguments
DRY_RUN=false
SKIP_USERS=false
SKIP_FIREWALL=false
SKIP_HARDENING=false
SKIP_LOGGING=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            show_usage
            exit $EXIT_SUCCESS
            ;;
        -n|--dry-run)
            DRY_RUN=true
            shift
            ;;
        --skip-users)
            SKIP_USERS=true
            shift
            ;;
        --skip-firewall)
            SKIP_FIREWALL=true
            shift
            ;;
        --skip-hardening)
            SKIP_HARDENING=true
            shift
            ;;
        --skip-logging)
            SKIP_LOGGING=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            show_usage
            exit $EXIT_ERROR
            ;;
    esac
done

main "$@"